### ISSUE TITLE
Add Contribution Guidelines in README.md

### ISSUE THREAD

**Issue by Swarnimashukla** [sajag1999/Website-Blocker-Project#10]
**Task**
Add contribution guidelines for PR generation . 

**Must include points** 
Claiming issues 
Adding UI screenshots for design related PR .
Create PR to specified branch 
Proper commit message 
(For reference purpose only)

Try to be more creative and elaborate your points properly. Check for open source projects take inspiration on how to create contribution guidelines 

Happy Learning 👍

**Comment by kichloo** [comment]
Can I take this issue?

**Comment by Swarnimashukla** [comment]
Sure @kichloo  but you can be assigned to only one issue at a time .
