### ISSUE TITLE
Add a nav bar to webpage

### ISSUE THREAD

**Issue by imsahil007** [sajag1999/Website-Blocker-Project#21]
**Task**

Add a navigation bar for the front-end page our to be website.

**Implementation**

The navbar can contain options like Home, About, Download, Contact us, etc.
It should be responsive and should work on small view-port devices as well.

**Procedure**

Claim this issue: Comment below that you want to work on this issue
Write a relevant commit message
Create a PR

All website discussion to be done  under #7

**Comment by kmrakash** [comment]
can i work on this issue ??

**Comment by kmrakash** [comment]
Do we have any particular design or any color pallete ready or i have to create myself one ? please assign and give brief details

**Comment by imsahil007** [comment]
> Do we have any particular design or any color pallete ready or i have to create myself one ? please assign and give brief details

Choose what's best for now. We will change it later if required.
