### ISSUE TITLE
Design HTML body 

### ISSUE THREAD

**Issue by imsahil007** [sajag1999/Website-Blocker-Project#25]
Add the content inside the body and make it look like the wireframe.
Make it more attractive

**Comment by kmrakash** [comment]
i'm interested in this issue please assign me

**Comment by kmrakash** [comment]
what  content should i add ??

**Comment by Swarnimashukla** [comment]
> what content should i add ??

@kichloo   please collaborate with @kmrakash  regarding this as you have worked on design part . You guys can refer to website links I provided in discussion issue

**Comment by Aakansha99** [comment]
I would also like to contribute in designing body part

**Comment by Swarnimashukla** [comment]
@Aakansha99  you are good to go now . Please share your designs here and after final approval create a pr for the same.

**Comment by kmrakash** [comment]
> I would also like to contribute in designing body part

Please let me know if you completed with design 😊 .

**Comment by Aakansha99** [comment]
I have made the PR of the design...its just a basic layout, we will add animations, different images to make it attractive. #44 
We can also use the GIFs from my blog https://medium.com/@jainaakansha28/title-85ac24cd6767
This will make our website look attractive.
Let me know if i need to modify something

**Comment by Swarnimashukla** [comment]
@Aakansha99  just checked your pr all assets are good and can be used but I can't find website layout you have share .ai image can you share it in png or other formats also include screenshot in your pr .

**Comment by Aakansha99** [comment]
Okay, i will add the jpg file too in it
