### ISSUE TITLE
Add logo 

### ISSUE THREAD

**Issue by Aakansha99** [sajag1999/Website-Blocker-Project#40]
Mentors if this issue is relevant . I would like to work on this issue please add SCI label and then assign me

**Comment by Swarnimashukla** [comment]
@Aakansha99  assigned . Share you design ideas here before final pr.

**Comment by Aakansha99** [comment]
Sure @Swarnimashukla. Do you have any design for reference

**Comment by Swarnimashukla** [comment]
As website has no name so far , go for something related to security , blocking etc. , basically a general logo design

**Comment by Aakansha99** [comment]
yeah, okay
