### ISSUE TITLE
Article/ Blog writing for SCI 

### ISSUE THREAD

**Issue by Swarnimashukla** [sajag1999/Website-Blocker-Project#50]
**Task**

If you are someone who likes to write articles you can write and share under this issue .

**Implementation**

Write an article on medium 

1. It can be your journey of SCI'20 so far and what you have learned
2. Article related to this project and technology used here 
3. Technical article on what could be improved in this project and how to take this forward (can include research work on current website present doing similar work as this project

**Procedure**

Claim this issue: Comment below that you want to work on this issue .
Write relevant commit message .
Create a PR .

**Comment by kichloo** [comment]
I want to take up this issue.

**Comment by kichloo** [comment]
I have written the blog.
Here's the link: https://medium.com/@vishalkichloo/my-journey-of-student-code-in-2020-fbd57d6efc61?sk=71b49dbc0bbc8dadcaf51c748f7966a0
