### ISSUE TITLE
Fix typos in README.md

### ISSUE THREAD

**Issue by Swarnimashukla** [sajag1999/Website-Blocker-Project#8]
**Task**
Check for errors in README.md and update it .

**Procedure**
Claim this issue: Comment below that you want to work on this issue .
Write relevant commit message .
Create a PR .

**Comment by kichloo** [comment]
@Swarnimashukla I can work on this issue. Please assign it to me.

**Comment by kichloo** [comment]
@Swarnimashukla Can I now work on this PR?
